[project]
name = "nastrajacz"
version = "0.1.0"
description = "Simple configuration manager for dotfiles and server configuration."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.0",
]
